import { CommandsEvent } from "../commands/index.js";
import { ContextEvent } from "../core/context/index.js";
import { MemoryEvent } from "../core/memory/index.js";
import { MessageEvent } from "../core/message/index.js";
import { ToolSchedulerEvent } from "../core/tool-scheduler/index.js";
import { PermissionEvent } from "../permission/index.js";
import { InteractionEvent } from "../runtime/interaction-broker/index.js";
import { SessionEvent } from "../services/session/index.js";
import type { BusEventDefinition } from "./index.js";

export type BusEventScope = "app" | "project" | "run" | "session";
export type BusEventAudience = "daemon" | "domain" | "tests" | "ui-projection";
export type BusEventFrequency = "high" | "low" | "medium";
export type BusEventContextStatus = "complete" | "known-gap";
export type BusEventUiVisibility = "no" | "via-projector" | "yes";

export interface BusEventCatalogEntry {
  readonly event: BusEventDefinition;
  readonly owner: string;
  readonly scope: BusEventScope;
  readonly audience: readonly BusEventAudience[];
  readonly frequency: BusEventFrequency;
  readonly requiredContext: readonly string[];
  readonly contextStatus: BusEventContextStatus;
  readonly uiVisible: BusEventUiVisibility;
  readonly decision: string;
}

export const allBusEvents = [
  CommandsEvent.Started,
  CommandsEvent.ResultDelivered,
  CommandsEvent.Failed,
  CommandsEvent.CatalogUpdated,
  InteractionEvent.Requested,
  InteractionEvent.Resolved,
  PermissionEvent.ModeChanged,
  PermissionEvent.LevelChanged,
  PermissionEvent.RuleAdded,
  PermissionEvent.Updated,
  PermissionEvent.Replied,
  MessageEvent.Updated,
  MessageEvent.Removed,
  MessageEvent.PartUpdated,
  MessageEvent.PartRemoved,
  ContextEvent.Compressed,
  ContextEvent.Pruned,
  ContextEvent.TurnPrepared,
  ContextEvent.CompactSkipped,
  MemoryEvent.Added,
  MemoryEvent.Updated,
  MemoryEvent.Removed,
  MemoryEvent.Refreshed,
  ToolSchedulerEvent.StatusChanged,
  ToolSchedulerEvent.ExecutionStarted,
  ToolSchedulerEvent.ExecutionCompleted,
  SessionEvent.Created,
  SessionEvent.Updated,
  SessionEvent.Removed,
] as const;

export const busEventCatalog: readonly BusEventCatalogEntry[] = [
  {
    event: CommandsEvent.Started,
    owner: "Commands",
    scope: "app",
    audience: ["ui-projection", "daemon", "tests"],
    frequency: "medium",
    requiredContext: ["commandRunId", "clientInvocationId", "timestamp"],
    contextStatus: "complete",
    uiVisible: "via-projector",
    decision: "Projected by Phase 1A app event projectors.",
  },
  {
    event: CommandsEvent.ResultDelivered,
    owner: "Commands",
    scope: "app",
    audience: ["ui-projection", "daemon", "tests"],
    frequency: "medium",
    requiredContext: ["commandRunId", "clientInvocationId", "timestamp"],
    contextStatus: "complete",
    uiVisible: "via-projector",
    decision: "Projected by Phase 1A app event projectors.",
  },
  {
    event: CommandsEvent.Failed,
    owner: "Commands",
    scope: "app",
    audience: ["ui-projection", "daemon", "tests"],
    frequency: "low",
    requiredContext: ["commandRunId", "clientInvocationId", "timestamp"],
    contextStatus: "complete",
    uiVisible: "via-projector",
    decision: "Projected by Phase 1A app event projectors.",
  },
  {
    event: CommandsEvent.CatalogUpdated,
    owner: "Commands",
    scope: "app",
    audience: ["ui-projection", "daemon", "tests"],
    frequency: "low",
    requiredContext: ["version", "timestamp"],
    contextStatus: "complete",
    uiVisible: "via-projector",
    decision: "Projected by Phase 1A app event projectors.",
  },
  {
    event: InteractionEvent.Requested,
    owner: "Interaction",
    scope: "app",
    audience: ["ui-projection", "daemon", "tests"],
    frequency: "medium",
    requiredContext: [
      "request.interactionId",
      "request.commandRunId",
      "timestamp",
    ],
    contextStatus: "complete",
    uiVisible: "via-projector",
    decision: "Projected by Phase 1A app event projectors.",
  },
  {
    event: InteractionEvent.Resolved,
    owner: "Interaction",
    scope: "app",
    audience: ["ui-projection", "daemon", "tests"],
    frequency: "medium",
    requiredContext: ["interactionId", "commandRunId", "timestamp"],
    contextStatus: "complete",
    uiVisible: "via-projector",
    decision: "Projected by Phase 1A app event projectors.",
  },
  {
    event: PermissionEvent.ModeChanged,
    owner: "Permission",
    scope: "app",
    audience: ["ui-projection", "tests"],
    frequency: "low",
    requiredContext: ["current", "previous"],
    contextStatus: "complete",
    uiVisible: "yes",
    decision: "Stateful in-process projection publishes permission.updated.",
  },
  {
    event: PermissionEvent.LevelChanged,
    owner: "Permission",
    scope: "app",
    audience: ["ui-projection", "tests"],
    frequency: "low",
    requiredContext: ["current", "previous"],
    contextStatus: "complete",
    uiVisible: "yes",
    decision: "Stateful in-process projection publishes permission.updated.",
  },
  {
    event: PermissionEvent.RuleAdded,
    owner: "Permission",
    scope: "session",
    audience: ["ui-projection", "tests"],
    frequency: "low",
    requiredContext: ["sessionId", "rule"],
    contextStatus: "complete",
    uiVisible: "yes",
    decision: "Stateful in-process projection publishes permission.updated.",
  },
  {
    event: PermissionEvent.Updated,
    owner: "Permission",
    scope: "run",
    audience: ["ui-projection", "tests"],
    frequency: "medium",
    requiredContext: [
      "info.sessionId",
      "info.messageId",
      "info.callId",
      "info.id",
    ],
    contextStatus: "complete",
    uiVisible: "yes",
    decision:
      "Stateful in-process projection publishes permission.requested; callId fallback remains legacy.",
  },
  {
    event: PermissionEvent.Replied,
    owner: "Permission",
    scope: "run",
    audience: ["ui-projection", "tests"],
    frequency: "medium",
    requiredContext: ["sessionId", "permissionId", "callId"],
    contextStatus: "complete",
    uiVisible: "yes",
    decision: "Stateful in-process projection publishes permission.resolved.",
  },
  {
    event: MessageEvent.Updated,
    owner: "Message",
    scope: "session",
    audience: ["domain", "tests"],
    frequency: "medium",
    requiredContext: ["info.sessionId", "info.id"],
    contextStatus: "complete",
    uiVisible: "no",
    decision:
      "Do not project directly because SDK has a different message.updated payload.",
  },
  {
    event: MessageEvent.Removed,
    owner: "Message",
    scope: "session",
    audience: ["domain", "tests"],
    frequency: "low",
    requiredContext: ["sessionId", "messageId"],
    contextStatus: "complete",
    uiVisible: "no",
    decision: "Internal domain event only.",
  },
  {
    event: MessageEvent.PartUpdated,
    owner: "Message",
    scope: "session",
    audience: ["domain", "tests"],
    frequency: "high",
    requiredContext: ["part.sessionId", "part.messageId", "part.id"],
    contextStatus: "complete",
    uiVisible: "no",
    decision:
      "Do not project directly because run stream owns message.part.delta.",
  },
  {
    event: MessageEvent.PartRemoved,
    owner: "Message",
    scope: "session",
    audience: ["domain", "tests"],
    frequency: "low",
    requiredContext: ["sessionId", "messageId", "partId"],
    contextStatus: "complete",
    uiVisible: "no",
    decision: "Internal domain event only.",
  },
  {
    event: ContextEvent.Compressed,
    owner: "Context",
    scope: "session",
    audience: ["domain", "tests"],
    frequency: "low",
    requiredContext: ["sessionId", "result"],
    contextStatus: "complete",
    uiVisible: "no",
    decision: "Internal domain event only.",
  },
  {
    event: ContextEvent.Pruned,
    owner: "Context",
    scope: "session",
    audience: ["domain", "tests"],
    frequency: "low",
    requiredContext: ["sessionId", "result"],
    contextStatus: "complete",
    uiVisible: "no",
    decision: "Internal domain event only.",
  },
  {
    event: ContextEvent.TurnPrepared,
    owner: "Context",
    scope: "session",
    audience: ["domain", "tests"],
    frequency: "medium",
    requiredContext: ["sessionId", "usage", "tookMs"],
    contextStatus: "complete",
    uiVisible: "no",
    decision: "Run stream owns user-visible run context events.",
  },
  {
    event: ContextEvent.CompactSkipped,
    owner: "Context",
    scope: "session",
    audience: ["domain", "tests"],
    frequency: "low",
    requiredContext: ["sessionId", "reason", "usage"],
    contextStatus: "complete",
    uiVisible: "no",
    decision: "Internal domain event only.",
  },
  {
    event: MemoryEvent.Added,
    owner: "Memory",
    scope: "project",
    audience: ["domain", "tests"],
    frequency: "low",
    requiredContext: ["scope", "text"],
    contextStatus: "known-gap",
    uiVisible: "no",
    decision:
      "Project memory lacks directory/projectRoot; keep internal until payload decision.",
  },
  {
    event: MemoryEvent.Updated,
    owner: "Memory",
    scope: "project",
    audience: ["domain", "tests"],
    frequency: "low",
    requiredContext: ["scope", "index", "newText"],
    contextStatus: "known-gap",
    uiVisible: "no",
    decision:
      "Project memory lacks directory/projectRoot; keep internal until payload decision.",
  },
  {
    event: MemoryEvent.Removed,
    owner: "Memory",
    scope: "project",
    audience: ["domain", "tests"],
    frequency: "low",
    requiredContext: ["scope", "index"],
    contextStatus: "known-gap",
    uiVisible: "no",
    decision:
      "Project memory lacks directory/projectRoot; keep internal until payload decision.",
  },
  {
    event: MemoryEvent.Refreshed,
    owner: "Memory",
    scope: "project",
    audience: ["domain", "tests"],
    frequency: "low",
    requiredContext: ["directory", "memory"],
    contextStatus: "complete",
    uiVisible: "no",
    decision: "Internal domain event only.",
  },
  {
    event: ToolSchedulerEvent.StatusChanged,
    owner: "ToolScheduler",
    scope: "run",
    audience: ["domain", "tests"],
    frequency: "high",
    requiredContext: ["callId", "toolName", "timestamp"],
    contextStatus: "known-gap",
    uiVisible: "no",
    decision:
      "Missing runId/sessionId/messageId; run stream owns visible tool events.",
  },
  {
    event: ToolSchedulerEvent.ExecutionStarted,
    owner: "ToolScheduler",
    scope: "run",
    audience: ["domain", "tests"],
    frequency: "high",
    requiredContext: ["callId", "toolName", "timestamp"],
    contextStatus: "known-gap",
    uiVisible: "no",
    decision:
      "Missing runId/sessionId/messageId; run stream owns visible tool events.",
  },
  {
    event: ToolSchedulerEvent.ExecutionCompleted,
    owner: "ToolScheduler",
    scope: "run",
    audience: ["domain", "tests"],
    frequency: "high",
    requiredContext: ["callId", "toolName", "timestamp"],
    contextStatus: "known-gap",
    uiVisible: "no",
    decision:
      "Missing runId/sessionId/messageId; run stream owns visible tool events.",
  },
  {
    event: SessionEvent.Created,
    owner: "Session",
    scope: "project",
    audience: ["domain", "tests"],
    frequency: "low",
    requiredContext: ["session.id", "session.projectRoot"],
    contextStatus: "complete",
    uiVisible: "no",
    decision: "Domain event; UI session projection remains separate.",
  },
  {
    event: SessionEvent.Updated,
    owner: "Session",
    scope: "project",
    audience: ["domain", "tests"],
    frequency: "low",
    requiredContext: ["session.id", "session.projectRoot"],
    contextStatus: "complete",
    uiVisible: "no",
    decision: "Domain event; UI session projection remains separate.",
  },
  {
    event: SessionEvent.Removed,
    owner: "Session",
    scope: "project",
    audience: ["domain", "tests"],
    frequency: "low",
    requiredContext: ["sessionId"],
    contextStatus: "complete",
    uiVisible: "no",
    decision: "Domain event; UI session projection remains separate.",
  },
];
