function table<TColumns extends Record<string, string>>(
  tableName: string,
  columns: TColumns,
): { readonly tableName: string; readonly columns: Readonly<TColumns> } {
  return { tableName, columns };
}

export const schema = {
  session: table("session", {
    id: "id",
    projectId: "project_id",
    projectRoot: "project_root",
    agent: "agent",
    parentId: "parent_id",
    title: "title",
    status: "status",
    createdAt: "created_at",
    updatedAt: "updated_at",
    messageCount: "message_count",
    lastMessageAt: "last_message_at",
    data: "data",
  }),
  message: table("message", {
    id: "id",
    sessionId: "session_id",
    contextScopeId: "context_scope_id",
    role: "role",
    agent: "agent",
    createdAt: "created_at",
    updatedAt: "updated_at",
    data: "data",
  }),
  part: table("part", {
    id: "id",
    messageId: "message_id",
    sessionId: "session_id",
    type: "type",
    orderIndex: "order_index",
    createdAt: "created_at",
    updatedAt: "updated_at",
    data: "data",
  }),
  runLedger: table("run_ledger", {
    endTimeSource: "end_time_source",
    inputsClosedAt: "inputs_closed_at",
    inputsCloseReason: "inputs_close_reason",
    runId: "run_id",
    sessionId: "session_id",
    contextScopeId: "context_scope_id",
    trigger: "trigger",
    status: "status",
    createdAt: "created_at",
    startedAt: "started_at",
    endedAt: "ended_at",
    error: "error",
    errorData: "error_data",
    ownerId: "owner_id",
    ownerPid: "owner_pid",
  }),
  appState: table("app_state", {
    scope: "scope",
    key: "key",
    value: "value",
    updatedAt: "updated_at",
  }),
  snapshotCheckpoint: table("snapshot_checkpoint", {
    checkpointId: "checkpoint_id",
    sessionId: "session_id",
    runId: "run_id",
    turnId: "turn_id",
    workdir: "workdir",
    workspaceSource: "workspace_source",
    messageCursorBefore: "message_cursor_before",
    messageCursorAfter: "message_cursor_after",
    preTreeRef: "pre_tree_ref",
    createdAt: "created_at",
  }),
  snapshotPatch: table("snapshot_patch", {
    patchId: "patch_id",
    checkpointId: "checkpoint_id",
    artifactPath: "artifact_path",
    postTreeRef: "post_tree_ref",
    fileCount: "file_count",
    createdAt: "created_at",
  }),
  goalRecord: table("goal_record", {
    sessionId: "session_id",
    seq: "seq",
    createdAt: "created_at",
    data: "data",
  }),
  subagentExecution: table("subagent_execution", {
    executionId: "execution_id",
    requestId: "request_id",
    parentSessionId: "parent_session_id",
    requesterScopeId: "requester_scope_id",
    requesterRunId: "requester_run_id",
    rootSessionId: "root_session_id",
    rootRunId: "root_run_id",
    rootPromptId: "root_prompt_id",
    subagentId: "subagent_id",
    mode: "mode",
    prompt: "prompt",
    timeoutMs: "timeout_ms",
    createdAt: "created_at",
    status: "status",
    childSessionId: "child_session_id",
    childScopeId: "child_scope_id",
    childRunId: "child_run_id",
    childUserMessageId: "child_user_message_id",
    delegationSequence: "delegation_sequence",
    startedAt: "started_at",
    completedAt: "completed_at",
    updatedAt: "updated_at",
    reason: "reason",
    output: "output",
    error: "error",
    artifact: "artifact",
    delivery: "delivery",
    lateResult: "late_result",
  }),
  subagentInstance: table("subagent_instance", {
    subagentId: "subagent_id",
    sessionId: "session_id",
    contextScopeId: "context_scope_id",
    parentSessionId: "parent_session_id",
    role: "role",
    name: "name",
    description: "description",
    initialPrompt: "initial_prompt",
    status: "status",
    output: "output",
    error: "error",
    pendingQueue: "pending_queue",
    currentInput: "current_input",
    currentRunId: "current_run_id",
    lastRunId: "last_run_id",
    timeoutMs: "timeout_ms",
    ownerId: "owner_id",
    ownerPid: "owner_pid",
    createdAt: "created_at",
    updatedAt: "updated_at",
    startedAt: "started_at",
    completedAt: "completed_at",
    interruptedAt: "interrupted_at",
    closedAt: "closed_at",
  }),
  workspaceRegistry: table("workspace_registry", {
    scopeKey: "scope_key",
    visibility: "visibility",
    position: "position",
    createdAt: "created_at",
    updatedAt: "updated_at",
    lastOpenedAt: "last_opened_at",
  }),
  promptSubmission: table("prompt_submission", {
    acceptedAt: "accepted_at",
    admissionOrder: "admission_order",
    endTimeSource: "end_time_source",
    steerReceipt: "steer_receipt",
    promptId: "prompt_id",
    clientRequestId: "client_request_id",
    scopeKey: "scope_key",
    sessionId: "session_id",
    userMessageId: "user_message_id",
    text: "text",
    namingSource: "naming_source",
    titleExpected: "title_expected",
    status: "status",
    runId: "run_id",
    ownerId: "owner_id",
    ownerPid: "owner_pid",
    editLeaseId: "edit_lease_id",
    editLeaseOwnerId: "edit_lease_owner_id",
    editLeaseExpiresAt: "edit_lease_expires_at",
    errorData: "error_data",
    createdAt: "created_at",
    updatedAt: "updated_at",
    startedAt: "started_at",
    endedAt: "ended_at",
  }),
  promptResubmission: table("prompt_resubmission", {
    scopeKey: "scope_key",
    operationId: "operation_id",
    promptId: "prompt_id",
    text: "text",
    receipt: "receipt",
  }),
  currentRunInput: table("current_run_input", {
    inputId: "input_id",
    runId: "run_id",
    sessionId: "session_id",
    source: "source",
    sourceId: "source_id",
    messageId: "message_id",
    acceptedAt: "accepted_at",
    data: "data",
  }),
  migration: table("migration", {
    version: "version",
    appliedAt: "applied_at",
  }),
} as const;
