function table<TColumns extends Record<string, string>>(
  tableName: string,
  columns: TColumns,
): { readonly tableName: string; readonly columns: Readonly<TColumns> } {
  return { tableName, columns };
}

export const schema = {
  session: table("session", {
    id: "id",
    projectId: "project_id",
    projectRoot: "project_root",
    agent: "agent",
    parentId: "parent_id",
    title: "title",
    status: "status",
    createdAt: "created_at",
    updatedAt: "updated_at",
    messageCount: "message_count",
    lastMessageAt: "last_message_at",
    data: "data",
  }),
  message: table("message", {
    id: "id",
    sessionId: "session_id",
    contextScopeId: "context_scope_id",
    role: "role",
    agent: "agent",
    createdAt: "created_at",
    updatedAt: "updated_at",
    data: "data",
  }),
  part: table("part", {
    id: "id",
    messageId: "message_id",
    sessionId: "session_id",
    type: "type",
    orderIndex: "order_index",
    createdAt: "created_at",
    updatedAt: "updated_at",
    data: "data",
  }),
  runLedger: table("run_ledger", {
    runId: "run_id",
    sessionId: "session_id",
    contextScopeId: "context_scope_id",
    trigger: "trigger",
    status: "status",
    createdAt: "created_at",
    startedAt: "started_at",
    endedAt: "ended_at",
    error: "error",
    ownerId: "owner_id",
    ownerPid: "owner_pid",
  }),
  appState: table("app_state", {
    scope: "scope",
    key: "key",
    value: "value",
    updatedAt: "updated_at",
  }),
  snapshotCheckpoint: table("snapshot_checkpoint", {
    checkpointId: "checkpoint_id",
    sessionId: "session_id",
    runId: "run_id",
    turnId: "turn_id",
    workdir: "workdir",
    workspaceSource: "workspace_source",
    messageCursorBefore: "message_cursor_before",
    messageCursorAfter: "message_cursor_after",
    preTreeRef: "pre_tree_ref",
    createdAt: "created_at",
  }),
  snapshotPatch: table("snapshot_patch", {
    patchId: "patch_id",
    checkpointId: "checkpoint_id",
    artifactPath: "artifact_path",
    postTreeRef: "post_tree_ref",
    fileCount: "file_count",
    createdAt: "created_at",
  }),
  goalRecord: table("goal_record", {
    sessionId: "session_id",
    seq: "seq",
    createdAt: "created_at",
    data: "data",
  }),
  subagentInstance: table("subagent_instance", {
    subagentId: "subagent_id",
    sessionId: "session_id",
    contextScopeId: "context_scope_id",
    parentSessionId: "parent_session_id",
    role: "role",
    name: "name",
    description: "description",
    initialPrompt: "initial_prompt",
    status: "status",
    output: "output",
    error: "error",
    pendingQueue: "pending_queue",
    currentRunId: "current_run_id",
    lastRunId: "last_run_id",
    timeoutMs: "timeout_ms",
    ownerId: "owner_id",
    ownerPid: "owner_pid",
    createdAt: "created_at",
    updatedAt: "updated_at",
    startedAt: "started_at",
    completedAt: "completed_at",
    interruptedAt: "interrupted_at",
    closedAt: "closed_at",
  }),
  migration: table("migration", {
    version: "version",
    appliedAt: "applied_at",
  }),
} as const;
