function table<TColumns extends Record<string, string>>(
  tableName: string,
  columns: TColumns,
): { readonly tableName: string; readonly columns: Readonly<TColumns> } {
  return { tableName, columns };
}

export const schema = {
  session: table("session", {
    id: "id",
    projectId: "project_id",
    projectRoot: "project_root",
    agent: "agent",
    parentId: "parent_id",
    title: "title",
    status: "status",
    createdAt: "created_at",
    updatedAt: "updated_at",
    messageCount: "message_count",
    lastMessageAt: "last_message_at",
    data: "data",
  }),
  message: table("message", {
    id: "id",
    sessionId: "session_id",
    role: "role",
    agent: "agent",
    createdAt: "created_at",
    updatedAt: "updated_at",
    data: "data",
  }),
  part: table("part", {
    id: "id",
    messageId: "message_id",
    sessionId: "session_id",
    type: "type",
    orderIndex: "order_index",
    createdAt: "created_at",
    updatedAt: "updated_at",
    data: "data",
  }),
  runLedger: table("run_ledger", {
    runId: "run_id",
    sessionId: "session_id",
    trigger: "trigger",
    status: "status",
    createdAt: "created_at",
    startedAt: "started_at",
    endedAt: "ended_at",
    error: "error",
  }),
  appState: table("app_state", {
    scope: "scope",
    key: "key",
    value: "value",
    updatedAt: "updated_at",
  }),
  snapshotCheckpoint: table("snapshot_checkpoint", {
    checkpointId: "checkpoint_id",
    sessionId: "session_id",
    runId: "run_id",
    turnId: "turn_id",
    workdir: "workdir",
    workspaceSource: "workspace_source",
    messageCursorBefore: "message_cursor_before",
    messageCursorAfter: "message_cursor_after",
    createdAt: "created_at",
  }),
  snapshotPatch: table("snapshot_patch", {
    patchId: "patch_id",
    checkpointId: "checkpoint_id",
    artifactPath: "artifact_path",
    fileCount: "file_count",
    createdAt: "created_at",
  }),
  migration: table("migration", {
    version: "version",
    appliedAt: "applied_at",
  }),
} as const;
