export const COMPRESSION_THRESHOLD = 0.85;
export const COMPRESSION_PRESERVE_RATIO = 0.3;
export const KEEP_RECENT_TOKENS = 20_000;
export const COMPACTION_MIN_REMAINING_INPUT_TOKENS = 4_096;
export const PRUNE_PROTECT_TOKENS = 40_000;
export const PRUNE_MINIMUM_TOKENS = 20_000;
export const SUMMARY_AGENT_NAME = "context";
